# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ultra96v2.xdc

# Block Designs: bd/ultra96v2/ultra96v2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2 || ORIG_REF_NAME==ultra96v2} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_zynq_ultra_ps_e_0_0_2/ultra96v2_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ultra96v2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_proc_sys_reset_0_0_2/ultra96v2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_proc_sys_reset_0_0 || ORIG_REF_NAME==ultra96v2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_clk_wiz_0_0_2/ultra96v2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_clk_wiz_0_0 || ORIG_REF_NAME==ultra96v2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_xlconcat_0_0_2/ultra96v2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_xlconcat_0_0 || ORIG_REF_NAME==ultra96v2_xlconcat_0_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_xlconcat_1_0_2/ultra96v2_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_xlconcat_1_0 || ORIG_REF_NAME==ultra96v2_xlconcat_1_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_proc_sys_reset_1_0_2/ultra96v2_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_proc_sys_reset_1_0 || ORIG_REF_NAME==ultra96v2_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_proc_sys_reset_2_0_2/ultra96v2_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_proc_sys_reset_2_0 || ORIG_REF_NAME==ultra96v2_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_proc_sys_reset_3_0_2/ultra96v2_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_proc_sys_reset_3_0 || ORIG_REF_NAME==ultra96v2_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_proc_sys_reset_4_0_2/ultra96v2_proc_sys_reset_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_proc_sys_reset_4_0 || ORIG_REF_NAME==ultra96v2_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_proc_sys_reset_5_0_2/ultra96v2_proc_sys_reset_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_proc_sys_reset_5_0 || ORIG_REF_NAME==ultra96v2_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_proc_sys_reset_6_0_2/ultra96v2_proc_sys_reset_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_proc_sys_reset_6_0 || ORIG_REF_NAME==ultra96v2_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/ultra96v2/ip/ultra96v2_rst_ps8_0_99M_0/ultra96v2_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_rst_ps8_0_99M_0 || ORIG_REF_NAME==ultra96v2_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: bd/ultra96v2/ultra96v2_ooc.xdc
